
jwt.secret=${JWT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-ms
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

# Product Service
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-ms
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/product/**

# Order Service
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://order-ms
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/orders/**

# Payment Service
spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://payment-ms
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/payments/**

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# =========================
# Logging
# =========================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO


management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
