server.port=8083

# ==========================
# Database
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/order-ms?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Eureka
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ==========================
# Resilience4j - Circuit Breaker
# ==========================
resilience4j.circuitbreaker.instances.product-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.product-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.product-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.product-service.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.product-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.product-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.product-service.registerHealthIndicator=true

# ==========================
# Retry
# ==========================
resilience4j.retry.instances.product-service.maxAttempts=3
resilience4j.retry.instances.product-service.waitDuration=2s

# ==========================
# Time Limiter
# ==========================
resilience4j.timelimiter.instances.product-service.timeoutDuration=5s

# ==========================
# Actuator
# ==========================
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always

# ==========================
# Distributed Tracing
# ==========================
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans


